package com.miaoshaproject.miaosha.dataobject;

import java.math.BigDecimal;

public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_order.id
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_order.user_id
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_order.item_id
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_order.amount
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_order.order_amount
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    private BigDecimal orderAmount;

    public Integer getPromoId() {
        return promoId;
    }

    public void setPromoId(Integer promoId) {
        this.promoId = promoId;
    }

    private Integer promoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_order.id
     *
     * @return the value of item_order.id
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_order.id
     *
     * @param id the value for item_order.id
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_order.user_id
     *
     * @return the value of item_order.user_id
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_order.user_id
     *
     * @param userId the value for item_order.user_id
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_order.item_id
     *
     * @return the value of item_order.item_id
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_order.item_id
     *
     * @param itemId the value for item_order.item_id
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_order.amount
     *
     * @return the value of item_order.amount
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_order.amount
     *
     * @param amount the value for item_order.amount
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_order.order_amount
     *
     * @return the value of item_order.order_amount
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_order.order_amount
     *
     * @param orderAmount the value for item_order.order_amount
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }
}