package com.miaoshaproject.miaosha.dataobject;

public class SequenceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.name
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.step
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    private Integer step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.start_sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    private Integer startSequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.max_sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    private Integer maxSequence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.name
     *
     * @return the value of sequence.name
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.name
     *
     * @param name the value for sequence.name
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.sequence
     *
     * @return the value of sequence.sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.sequence
     *
     * @param sequence the value for sequence.sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.step
     *
     * @return the value of sequence.step
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.step
     *
     * @param step the value for sequence.step
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.start_sequence
     *
     * @return the value of sequence.start_sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    public Integer getStartSequence() {
        return startSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.start_sequence
     *
     * @param startSequence the value for sequence.start_sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    public void setStartSequence(Integer startSequence) {
        this.startSequence = startSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.max_sequence
     *
     * @return the value of sequence.max_sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    public Integer getMaxSequence() {
        return maxSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.max_sequence
     *
     * @param maxSequence the value for sequence.max_sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    public void setMaxSequence(Integer maxSequence) {
        this.maxSequence = maxSequence;
    }
}