package com.miaoshaproject.miaosha.dao;

import com.miaoshaproject.miaosha.dataobject.OrderDO;

public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_order
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_order
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    int insert(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_order
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    int insertSelective(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_order
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    OrderDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_order
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_order
     *
     * @mbg.generated Mon Jun 20 17:28:10 GMT+08:00 2022
     */
    int updateByPrimaryKey(OrderDO row);
}