package com.miaoshaproject.miaosha.dao;

import com.miaoshaproject.miaosha.dataobject.SequenceDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    int insert(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    int insertSelective(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    SequenceDO selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 20 16:09:01 GMT+08:00 2022
     */
    int updateByPrimaryKey(SequenceDO row);
}