package com.miaoshaproject.miaosha.dao;

import com.miaoshaproject.miaosha.dataobject.StockLogDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface StockLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Sun Jul 10 16:30:28 GMT+08:00 2022
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Sun Jul 10 16:30:28 GMT+08:00 2022
     */
    int insert(StockLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Sun Jul 10 16:30:28 GMT+08:00 2022
     */
    int insertSelective(StockLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Sun Jul 10 16:30:28 GMT+08:00 2022
     */
    StockLogDO selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Sun Jul 10 16:30:28 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(StockLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Sun Jul 10 16:30:28 GMT+08:00 2022
     */
    int updateByPrimaryKey(StockLogDO row);
}